from typing import Protocol

from tickets.models import TicketDraft, TicketRecord


class OwnershipConflict(ValueError):
    pass


class SupportRepository(Protocol):
    async def session(self, thread_id: str) -> dict | None: ...
    async def register(self, user_id: str, thread_id: str, title: str) -> dict: ...
    async def sessions(self, user_id: str, limit: int) -> list[dict]: ...
    async def create(
        self, draft: TicketDraft, draft_id: str, version: int, thread_id: str, user_id: str
    ) -> TicketRecord: ...
    async def get(self, ticket_id: str, user_id: str) -> TicketRecord | None: ...
    async def by_request(
        self, draft_id: str, thread_id: str, user_id: str
    ) -> TicketRecord | None: ...
    async def tickets(self, user_id: str, limit: int) -> list[TicketRecord]: ...
